AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless deployment for ResumeForge on AWS Lambda and API Gateway.

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: Stage name for the API Gateway deployment.
  DataBucketName:
    Type: String
    Default: resume-forge-data
    Description: Globally unique name for the S3 bucket that stores uploads and generated artifacts.
  CreateDataBucket:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: >-
      Set to 'false' to use an existing S3 bucket specified in DataBucketName
      instead of creating a new one.
  ResumeTableName:
    Type: String
    Default: ResumeForge
    Description: Name of the DynamoDB table that tracks processed resumes.
  CreateResumeTable:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: >-
      Set to 'false' to use an existing DynamoDB table specified in ResumeTableName
      instead of creating a new one.

Conditions:
  CreateResumeTableCondition: !Equals [!Ref CreateResumeTable, 'true']
  CreateDataBucketCondition: !Equals [!Ref CreateDataBucket, 'true']

Resources:
  ResumeForgeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - multipart/form-data
        - application/pdf
        - application/octet-stream
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  DataBucket:
    Type: AWS::S3::Bucket
    Condition: CreateDataBucketCondition
    Properties:
      BucketName: !Ref DataBucketName
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ResumeForgeTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateResumeTableCondition
    Properties:
      TableName: !Ref ResumeTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: linkedinProfileUrl
          AttributeType: S
      KeySchema:
        - AttributeName: linkedinProfileUrl
          KeyType: HASH

  ResumeForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ResumeForgeHandler
      Handler: lambda.handler
      Runtime: nodejs18.x
      MemorySize: 2048
      Timeout: 300
      Events:
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeForgeApi
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeForgeApi
            Path: /
            Method: ANY
      Environment:
        Variables:
          S3_BUCKET: !Ref DataBucketName
          RESUME_TABLE_NAME: !Ref ResumeTableName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: AllowBucketAccess
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${DataBucketName}/*
        - DynamoDBCrudPolicy:
            TableName: !Ref ResumeTableName
      Layers: []

  ResumeForgeCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Disable caching; viewer context is forwarded via a dedicated origin request policy.
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        Name: !Sub ResumeForgeCachePolicy-${AWS::StackName}
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  ResumeForgeOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Comment: Forward required headers while letting CloudFront supply the Host header expected by API Gateway.
        Name: !Sub ResumeForgeOriginRequestPolicy-${AWS::StackName}
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Authorization
            - Content-Type
            - Origin
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Accept
        QueryStringsConfig:
          QueryStringBehavior: all

  ResumeForgeDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - ResumeForgeApi
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: API Gateway distribution for ResumeForge
        Origins:
          - Id: ResumeForgeApiOrigin
            DomainName: !Sub "${ResumeForgeApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "/${StageName}"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: ResumeForgeApiOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          CachePolicyId: !GetAtt ResumeForgeCachePolicy.Id
          OriginRequestPolicyId: !GetAtt ResumeForgeOriginRequestPolicy.Id

Outputs:
  ApiBaseUrl:
    Description: Invoke URL for the API Gateway stage.
    Value: !Sub https://${ResumeForgeApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  AppBaseUrl:
    Description: Primary CloudFront URL for the ResumeForge front page and API access.
    Value: !Sub https://${ResumeForgeDistribution.DomainName}
  DataBucket:
    Description: Bucket used for uploads and generated files.
    Value: !If [CreateDataBucketCondition, !Ref DataBucket, !Ref DataBucketName]
  ResumeTable:
    Description: DynamoDB table that stores resume processing metadata.
    Value: !If [CreateResumeTableCondition, !Ref ResumeForgeTable, !Ref ResumeTableName]
  CloudFrontUrl:
    Description: CloudFront distribution domain for accessing the API.
    Value: !Sub https://${ResumeForgeDistribution.DomainName}
