export const resumeSamples = {
  productEngineer: {
    description: `We need a senior product engineer to lead end-to-end delivery of web experiences. Key focuses: React, Node.js, experimentation, API design, accessibility, data instrumentation, mentoring, growth mindset.`,
    jobSkills: [
      'React',
      'Node.js',
      'Experimentation',
      'API design',
      'Accessibility',
      'Data instrumentation',
      'Mentoring',
      'Growth mindset',
    ],
    resumeText: `SOFIA RAMIREZ\nSan Francisco, CA • sofia@example.com • github.com/sofiaramirez\n\nSUMMARY\nProduct-focused software engineer delivering reliable, accessible web experiences for 15M monthly users. Led experimentation and mentoring initiatives that lifted growth KPIs.\n\nEXPERIENCE\nSenior Product Engineer — Loop Labs (2021–Present)\n- Directed React and Node.js modernization of experimentation platform, cutting test launch time 40% while raising velocity by 18%.\n- Designed resilient APIs with TypeScript and GraphQL, processing 65M events/day with <0.2% error rate.\n- Partnered with design to ship WCAG AA accessible UI kits across 12 surfaces.\n- Mentored 6 engineers, establishing instrumentation guardrails adopted org-wide.\n\nProduct Engineer — Brightline (2018–2021)\n- Built experimentation dashboards that improved activation by 9%.\n- Introduced growth mindset workshops for engineers and PMs.\n\nPROJECTS\nImpact Review Automation — Automated insight pack generation for experiment reviews using GPT APIs, saving 30 hours/quarter.\n\nEDUCATION\nB.S. Computer Science, University of Texas at Austin\n\nSKILLS\nReact, Node.js, GraphQL, Accessibility, Experimentation, Mentoring, Data instrumentation, TypeScript`,
    resumeSkills: [
      'React',
      'Node.js',
      'GraphQL',
      'Accessibility',
      'Experimentation',
      'Mentoring',
      'Data instrumentation',
      'TypeScript',
    ],
  },
  operationsManager: {
    description: `Operations lead needed to optimize logistics, reduce cost leakage, and partner with finance. Must communicate clearly and avoid heavy formatting that breaks ATS.`,
    jobSkills: [
      'Logistics',
      'Cost reduction',
      'Finance partnership',
      'Process improvement',
      'Vendor management',
    ],
    resumeText: `DANIELLE PEREZ\nPortfolio: danielleperez.example.com\n\nPROFILE\nOperational leader scaling fulfillment for retail brands.\n\nTABLE OF CONTENTS\n| Section | Details |\n|--------|---------|\n| Experience | Multi-location oversight |\nPage 1 of 2\n\nWORK HISTORY\nRegional Operations Manager — Urban Cart (2020–Present)\n• Rebuilt routing templates and saved $1.1M transportation spend annually.\n• Negotiated vendor SLAs reducing late deliveries 32%.\n• Created reporting cadences with finance for weekly variance reviews.\n\nSenior Operations Analyst — QuickDrop (2016–2020)\n• Led process improvement across six warehouses; standardized playbooks.\n• Introduced KPI scorecards and cross-functional standups.\n\nEDUCATION\nB.S. Industrial Engineering, Cal Poly\n\nSKILLS\nLogistics, Vendor Management, Process Improvement, Finance partnership, Tableau`,
    resumeSkills: [
      'Logistics',
      'Vendor Management',
      'Process Improvement',
      'Finance partnership',
      'Tableau',
    ],
  },
  academicResearcher: {
    description: `University lab seeks research scientist with publications, grant leadership, and collaborative outreach.`,
    jobSkills: [
      'Research',
      'Publications',
      'Grants',
      'Collaboration',
      'Data analysis',
      'Python',
    ],
    resumeText: `DR. ALEX CHEN\nBoston, MA | alex.chen@example.edu\n\nSUMMARY\nResearch scientist translating computational biology insights into clinical partnerships.\n\nRESEARCH EXPERIENCE\nLead Scientist — Genomic Insight Lab (2017–Present)\n- Spearheaded NIH-funded study integrating single-cell sequencing; published 4 first-author papers in Nature Medicine.\n- Collaborated with cross-institution teams to launch clinical pilots across 3 hospitals.\n- Mentored 8 graduate researchers; instituted reproducible Python tooling adopted across lab.\n\nEDUCATION\nPh.D. Computational Biology, MIT\nB.S. Bioengineering, Rice University\n\nPUBLICATIONS\nChen, A., et al. Nature Medicine 2023.\nChen, A., et al. Cell 2022.\n\nGRANTS\nPrincipal Investigator — NIH R01 HG012345 (2022–2027).\nCo-Investigator — NSF Expedition in Computing (2019–2023).\n\nSKILLS\nPython, R, Data analysis, Grant writing, Collaboration, Scientific communication`,
    resumeSkills: [
      'Python',
      'R',
      'Data analysis',
      'Grant writing',
      'Collaboration',
      'Scientific communication',
    ],
  },
  minimalistDesigner: {
    description: `Creative studio wants designers with clear storytelling but expects structured resume with portfolio context.`,
    jobSkills: [
      'Design systems',
      'Stakeholder communication',
      'Prototyping',
      'Figma',
    ],
    resumeText: `LI WEI\nDesigner\n\nEXPERIENCE\nDesign things\nDid other design things\n\nPORTFOLIO\nliwei.design\n\nAWARDS\nMade up award`,
    resumeSkills: ['Design', 'Figma'],
  },
};
